# Generated by Django 5.2.4 on 2025-11-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_fcmtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(verbose_name='FCM Token'),
        ),
    ]
