# Generated by Django 5.2.4 on 2025-11-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_alerts', models.PositiveIntegerField(default=0, verbose_name='Total Alerts')),
                ('total_alerts_resolved', models.PositiveIntegerField(default=0, verbose_name='Total Alerts Resolved')),
                ('total_alerts_pending', models.PositiveIntegerField(default=0, verbose_name='Total Alerts Pending')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
    ]
