# Generated by Django 5.2.4 on 2025-11-13 17:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('boundary_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Área límite')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='member', max_length=50, verbose_name='Rol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.community', verbose_name='Comunidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_memberships_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Membresía de comunidad',
                'verbose_name_plural': 'Membresías de comunidades',
                'db_table': 'community_membership',
                'constraints': [models.UniqueConstraint(fields=('user', 'community'), name='unique_user_community_membership')],
            },
        ),
    ]
