# Generated by Django 5.2.4 on 2025-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('boundary_area', models.JSONField(blank=True, null=True, verbose_name='Área límite')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'community',
            },
        ),
    ]
