# Generated by Django 5.2.4 on 2025-10-18 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='member', max_length=50, verbose_name='Rol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.community', verbose_name='Comunidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Membresía de comunidad',
                'verbose_name_plural': 'Membresías de comunidades',
                'db_table': 'community_membership',
                'constraints': [models.UniqueConstraint(fields=('user', 'community'), name='unique_user_community_membership')],
            },
        ),
    ]
