version: "3.9"
services:
  postgres:
    image: postgres
    container_name: pg-sql
    restart: always
    ports:
      - "5435:5432"
    expose:
      - "5435"
    environment:
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      PGDATABASE: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - psql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - psql

volumes:
  database-data:
  pgadmin-data:

networks:
  psql:
    name: network-admin-psql
