# Generated by Django 5.2.4 on 2025-11-13 17:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de incidente',
                'verbose_name_plural': 'Estados de incidentes',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Color HEX')),
                ('default_severity', models.IntegerField(blank=True, null=True, verbose_name='Severidad predeterminada')),
                ('requires_authority', models.BooleanField(default=False, verbose_name='Requiere autoridad')),
            ],
            options={
                'verbose_name': 'Tipo de incidente',
                'verbose_name_plural': 'Tipos de incidentes',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Ubicación')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anónimo')),
                ('severity_level', models.IntegerField(blank=True, null=True, verbose_name='Nivel de severidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del suceso')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('reported_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_by_reported_user', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('incident_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.incidentstatus', verbose_name='Estado')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.incidenttype', verbose_name='Tipo de incidente')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anónimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incident.incident', verbose_name='Incidente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de incidente',
                'verbose_name_plural': 'Comentarios de incidentes',
            },
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=20, verbose_name='Tipo de medio')),
                ('file', models.FileField(blank=True, null=True, upload_to='incidents/%Y/%m/%d/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='incident.incident', verbose_name='Incidente')),
            ],
            options={
                'verbose_name': 'Archivo multimedia',
                'verbose_name_plural': 'Archivos multimedia',
            },
        ),
    ]
