# Generated by Django 5.2.4 on 2025-11-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de notificación')),
                ('was_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incident.incident', verbose_name='Incidente')),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario notificado')),
            ],
            options={
                'verbose_name': 'Notificación de Incidente',
                'verbose_name_plural': 'Notificaciones de Incidentes',
                'db_table': 'incident_notification',
                'ordering': ['-notification_sent_at'],
                'indexes': [models.Index(fields=['notified_user', '-notification_sent_at'], name='incident_no_notifie_262e20_idx'), models.Index(fields=['incident', 'notified_user'], name='incident_no_inciden_a25ab2_idx')],
                'constraints': [models.UniqueConstraint(fields=('incident', 'notified_user'), name='unique_incident_notification_per_user')],
            },
        ),
    ]
