# Generated by Django 5.2.4 on 2025-10-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incident_created_at_incident_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
