# Generated by Django 5.2.4 on 2025-11-06 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_remove_incident_location_incident_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='community',
        ),
        migrations.RemoveField(
            model_name='incidentmedia',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='incidentmedia',
            name='file_url',
        ),
        migrations.AddField(
            model_name='incidentmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='incidents/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del suceso'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha del reporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
    ]
