# Generated by Django 5.2.4 on 2025-11-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_remove_incident_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='Ubicación'),
        ),
    ]
