# Generated by Django 5.2.4 on 2025-11-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_remove_incident_latitude_remove_incident_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
