# Generated by Django 5.2.4 on 2025-11-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_incident_latitude_incident_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
    ]
